### ISSUE TITLE
sw360docs may be worth to be in sw360.web page 

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360.website#10]
https://github.com/eclipse/sw360/tree/master/frontend/sw360-portlet/src/documentation/sw360docs

**Comment by heliocastro** [comment]
Documents copied to main doc website.
Reference commits:
https://github.com/eclipse/sw360.website/commit/c61ddf9ae168cc094b5c0681056e618816da5f7c
https://github.com/eclipse/sw360.website/commit/d9ed054d6c5db450160adaad73b478b082439599
https://github.com/eclipse/sw360.website/commit/ee34c82a7f63206559e05678b64ec0ba4a6ab5f2
https://github.com/eclipse/sw360.website/commit/85ce57e88794540d7427969cbef5692e40698591
