### ISSUE TITLE
Not able to build webpage on local environment because "module "docsy" not found;"

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360.website#15]
> hama@hama:~/sw360.website$ bash docker_serve_local.sh 
Open local browser on port 1313
Unable to find image 'klakegg/hugo:0.93.2-ext-ubuntu' locally
0.93.2-ext-ubuntu: Pulling from klakegg/hugo
cf06a7c31611: Pull complete 
1cc8ffae1b4a: Pull complete 
999911a5a482: Pull complete 
6b4395f9a69c: Pull complete 
18cdba58533d: Pull complete 
52c92b8d7d39: Pull complete 
Digest: sha256:fe16324340ae912a8bbf50f181d6d5fe922b77b1e70af7bd903ba8e113a47ab1
Status: Downloaded newer image for klakegg/hugo:0.93.2-ext-ubuntu
hugo: downloading modules …
Error: module "docsy" not found; either add it as a Hugo Module or store it in "/src/themes".: module does not exist
hugo: collected modules in 8304 ms

**Comment by heliocastro** [comment]
Hugo get mod is failing to create the support directories, so as workaround an step need to be added:
```bash
mkdir themes/docsy
```
This is added on docker_serve script now.
